import { useMemo, useState } from 'react';
import { ArrowUpRight, Download, LockKeyhole, RotateCcw } from 'lucide-react';
import { aggregateOutcomes, getFilterOptions, downloadAggregateJson, DEFAULT_FILTERS, type OutcomesDataset, type OutcomeFilters } from '../lib/outcomes';
import CohortChart from './CohortChart';

const n=(value:number)=>value.toLocaleString('en-US');
const p=(value:number|null)=>value===null?'—':`${(value*100).toFixed(1)}%`;
export default function Impact({dataset,filters,onFiltersChange}:{dataset:OutcomesDataset;filters:OutcomeFilters;onFiltersChange:(filters:OutcomeFilters)=>void}){
  const summary=useMemo(()=>aggregateOutcomes(dataset,filters),[dataset,filters]);
  const options=useMemo(()=>getFilterOptions(dataset),[dataset]);
  const [allMetrics,setAllMetrics]=useState(false);
  const firstIds=['students','deployment','deployDays','assessment'];
  const kpis=allMetrics?summary.kpis:firstIds.map(id=>summary.kpis.find(k=>k.id===id)!);
  const timing=[{label:'0–1',min:0,max:1},{label:'2–3',min:2,max:3},{label:'4–7',min:4,max:7},{label:'8–14',min:8,max:14},{label:'15–30',min:15,max:30},{label:'31–60',min:31,max:60},{label:'61+',min:61,max:Infinity}].map(b=>({...b,count:summary.deployDays.reduce((s,r)=>s+(r.days>=b.min&&r.days<=b.max?r.count:0),0)}));
  const maxTiming=Math.max(1,...timing.map(t=>t.count));
  const hasFilter=Object.values(filters).some(v=>v!=='all');
  return <div className="impact-view">
    <div className="page-header page-header--actions"><div><span className="eyebrow">AI PIONEER · IMPACT OBSERVATORY</span><h1>An expanding field<br/>of possibility<span>.</span></h1><p>Explore the AI Pioneer reference model. Every number here is modeled, not an observed program result.</p></div><button className="button-outline" onClick={()=>downloadAggregateJson(summary)}><Download size={17}/>Download view</button></div>
    <div className="filter-bar"><div className="cohort-filters"><span className="filter-label">Cohort</span><div className="segmented">{options.cohort.map(o=><button key={o.value} aria-pressed={filters.cohort===o.value} disabled={o.disabled} title={o.disabled?'2027 is sealed. Release reference: March 30, 2027, Eastern time. New data must be published.':undefined} onClick={()=>onFiltersChange({...filters,cohort:o.value as OutcomeFilters['cohort']})}>{o.value==='all'?'All cohorts':o.value}{o.disabled&&<LockKeyhole size={11}/>}</button>)}</div></div><div className="select-filters">{([{key:'track',label:'Build track'},{key:'jurisdiction',label:'Jurisdiction'},{key:'delivery',label:'Delivery'}] as const).map(f=><label key={f.key}><span>{f.label}</span><select value={filters[f.key]} onChange={e=>onFiltersChange({...filters,[f.key]:e.target.value})}>{options[f.key].map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>)}{hasFilter&&<button className="icon-button" title="Reset all filters" aria-label="Reset all filters" onClick={()=>onFiltersChange({...DEFAULT_FILTERS})}><RotateCcw size={17}/></button>}</div></div>
    <div className="impact-data-caption"><span className="modeled-label">MODELED · {n(summary.students)} RECORDS IN VIEW</span><button className="text-button" onClick={()=>setAllMetrics(v=>!v)}>{allMetrics?'Show key metrics':'Show all eight metrics'}</button></div>
    <div className="impact-kpis">{kpis.map(k=><div key={k.id} className="kpi"><strong>{k.formatted}{k.id==='deployDays'&&k.value!==null&&<small>d</small>}</strong><span>{k.label}</span><details><summary>{k.detail}</summary><p>{k.definition}</p></details></div>)}</div>
    {summary.students===0?<div className="empty-state"><h2>No modeled records match this view.</h2><p>Try another combination of build track, jurisdiction, and delivery.</p><button className="button-outline" onClick={()=>onFiltersChange({...DEFAULT_FILTERS})}>Reset filters</button></div>:<>
      <div className="impact-main-grid"><CohortChart rows={summary.cohorts} selected={filters.cohort} onSelect={year=>onFiltersChange({...filters,cohort:year as OutcomeFilters['cohort']})}/><section className="panel progression"><div className="panel-heading"><div><h2>From learning to launching.</h2><p>Share reaching each milestone or beyond.</p></div></div><div className="stage-list">{summary.stages.filter(s=>[0,1,2,3,5,7].includes(s.stage)).map(s=><div key={s.stage} className="stage-row"><div><span className="stage-code">S{s.stage}</span><span>{s.stage===0?'Enrolled':s.label}</span><strong>{p(s.rate)}</strong></div><div className="stage-track"><span style={{width:`${(s.rate||0)*100}%`}}/></div></div>)}</div><p className="chart-note">Denominator: all learners in this view. Modeled progression.</p></section></div>
      <div className="impact-secondary-grid"><section className="panel assessments"><div className="panel-heading"><div><h2>Understanding, expanded.</h2><p>Mean assessment scores · 0–100 points.</p></div><div className="chart-legend"><span><i style={{background:'var(--chart-3)'}}/>Before</span><span><i style={{background:'var(--accent)'}}/>After</span></div></div><div className="assessment-list">{summary.assessments.map(a=><div key={a.key} className="assessment-row"><div><span>{a.label}</span><strong>{a.gain===null?'—':`${a.gain>=0?'+':''}${a.gain.toFixed(1)}`}</strong></div><div className="assessment-track"><span style={{width:`${a.pre??0}%`}}/><span style={{width:`${a.post??0}%`}}/></div><div className="assessment-scores"><span>Before {a.pre===null?'—':a.pre.toFixed(1)}</span><span>After {a.post===null?'—':a.post.toFixed(1)}</span></div></div>)}</div><p className="chart-note">Descriptive pre/post change. No comparison group or causal attribution.</p></section>
      <section className="panel timing"><div className="panel-heading"><div><h2>The first live deployment.</h2><p>Days from enrollment to first live URL.</p></div></div><div className="timing-chart">{timing.map(t=><div className="timing-column" key={t.label}><span className="timing-value">{summary.deployed?p(t.count/summary.deployed):'—'}</span><div className="timing-bar-slot"><div style={{height:`${t.count/maxTiming*100}%`}} title={`${t.label} days: ${n(t.count)} modeled deployed learners`}/></div><span>{t.label}</span></div>)}</div><div className="timing-summary"><strong>{summary.medianDaysToDeploy??'—'}<span>days</span></strong><p>Median to first deploy<br/><small>Among {n(summary.deployed)} modeled deployed learners.</small></p></div></section></div>
      <section className="panel geography"><div className="panel-heading"><div><h2>A wider circle of possibility.</h2><p>Modeled reach across jurisdictions. Select one to inspect.</p></div><span className="source-label">{summary.jurisdictions} in view</span></div><div className="jurisdiction-grid">{summary.jurisdictionRows.map(r=><button className={filters.jurisdiction===r.code?'is-selected':''} key={r.code} onClick={()=>onFiltersChange({...filters,jurisdiction:filters.jurisdiction===r.code?'all':r.code})} aria-pressed={filters.jurisdiction===r.code} aria-label={`${r.code}: ${n(r.students)} modeled learners. Filter jurisdiction.`}><span>{r.code}</span><strong>{n(r.students)}</strong><i style={{height:`${Math.max(8,r.students/Math.max(...summary.jurisdictionRows.map(j=>j.students))*65)}px`}}/></button>)}</div><p className="chart-note">Jurisdiction context keeps all jurisdictions visible under the other filters. Counts are synthetic.</p></section>
    </>}
    <div className="impact-bottom"><p>The reference model is a design and analytical input. It does not represent verified live platform activity.</p><a className="text-button" href="/reference/outcomes-explorer.html" target="_blank" rel="noreferrer">Open the full reference explorer <ArrowUpRight size={16}/></a></div>
  </div>;
}
